name: 'Create branch type from tag'
description: 'create branch type from tag pushed by the user'
inputs:
  tagName:
    description: 'the tag name'
    required: true
    default: ''
  tagCommitHash:
    description: 'the tag commit id'
    required: true
    default: ''
  gitUserName:
    description: 'git user name'
    required: true
    default: ''
  gitUserEmail:
    description: 'git user email'
    required: true
    default: ''
outputs:
  scriptOutput: 
    description: "script output"
    value: ''
runs:
  using: "composite"
  steps: 
    - run: ${{ github.action_path }}/branch.sh ${{ inputs.tagName }} ${{ inputs.tagCommitHash }} ${{ inputs.gitUserName }} ${{ inputs.gitUserEmail }}
      shell: bash
