name: create-release-branch-from-tag
on:
  create:
    tags:
    - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set vars
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "RELEASE_HASH=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
      - name: Print release info
        run: |
          echo "release tag/version: $RELEASE_VERSION"
          echo "release commit id: $RELEASE_HASH"
      - name: Create branch and split point
        run: |
          set -x
          BRANCH_SPLIT_NAME="${{ env.RELEASE_VERSION }}_branch_split"
          echo "BRANCH_SPLIT_NAME: $BRANCH_SPLIT_NAME"
          
          BRANCH_HOTFIX="${{ env.RELEASE_VERSION }}_hotfix"
          echo "BRANCH_HOTFIX: $BRANCH_HOTFIX" 
          
          git config --global user.name "alcide jenkins"
          git config --global user.email "alcidejenkins@rapid7.com"

          git branch ${{ env.RELEASE_VERSION }} ${{ env.RELEASE_HASH }}
          git push -u origin refs/heads/${{ env.RELEASE_VERSION }}:refs/heads/${{ env.RELEASE_VERSION }} 

          git tag -a $BRANCH_SPLIT_NAME ${{ env.RELEASE_HASH }} -m "tag ${{ env.RELEASE_VERSION }} split point from master with tag: $BRANCH_SPLIT_NAME"
          git push origin $BRANCH_SPLIT_NAME

          git branch $BRANCH_HOTFIX ${{ env.RELEASE_HASH }}
          git push origin $BRANCH_HOTFIX 
          set +x
